Implemented anatomic incrementing of key version in Memcache(d)
W3EDGE/w3-total-cache pull request #253
Opened 2020-08-26 12:26 UTC by SeBsZ

to prevent race conditions

2020-09-04 15:50 UTC, cssjoe requested changes
Please format the new/updated lines of code to adhere to WordPress coding standards -- https://make.wordpress.org/core/handbook/best-practices/coding-standards/

Use tabs to indent rather than spaces.  Pad function parameters with one space.

Thank you.

2020-09-04 15:50 UTC, cssjoe commented on Cache_Memcache.php
> +        $this->_increment_key_version($group);
As per WordPress code standards, please format using tabs to indent and spaces around parameters.
`		$this->_increment_key_version( $group );`

2020-09-09 13:37 UTC, SeBsZ commented
I fixed the tabs and spaces

2020-09-09 14:58 UTC, maxicus approved these changes

2020-09-09 16:54 UTC, cssjoe approved these changes

2020-09-09 16:55 UTC, merged

2020-09-09 16:56 UTC, cssjoe commented
Thank you @SeBsZ