Remove serialize/unserialize from APCu cache.
W3EDGE/w3-total-cache pull request #283
Opened 2020-10-05 18:45 UTC by mongeron

https://github.com/W3EDGE/w3-total-cache/issues/281

I have tested these changes briefly with a WordPress installation that has WP object caching enabled, and the caching is used in plugin code. I haven't encountered any issues.

However, proper testing should still be performed against the changes, although they are trivial in a way.

2020-10-07 15:37 UTC, maxicus approved these changes

2020-10-16 19:18 UTC, cssjoe requested changes
Our automated tests show "cache key ... no entry found" errors.  When working correctly, the HTML pages should contain "using apc" and not indicate cache key errors.

2020-10-21 12:18 UTC, maxicus requested changes
QA results show behavior is unstable.
Most tests fail.

Didn't investigate personally since change is not a priority and not in a roadmap.

2020-10-21 15:57 UTC, mongeron commented
Tests are most likely written with different expectations and I didn't check them. I will look into fixing them.

The patched version has been running on production servers since I created the patch so it looks stable to me.

2020-10-21 16:13 UTC, mongeron commented
Tests most likely fail because tests are only run using `Cache_Apc` class, while the main plugin is using `Cache_Apcu` class or `Cache_Apc` class, depending on the existence of `apcu_store()` function. This is checked on Cache.php line 32.

I will remove the serialization also from Cache_Apc.php and see if I can run the tests myself.

2020-11-09 18:00 UTC, cssjoe commented
@mongeron We will be happy to review your new changes.  Have you had a chance to perform additional testing?  I suspect that most users that enable APC use APCu.

2020-11-17 13:48 UTC, cssjoe commented
We can look into this possible optimization in the future if there is a greater need for it, and it can pass all automated tests.

2020-11-17 13:48 UTC, closed without merging

2020-11-17 14:02 UTC, watou commented
> Didn't investigate personally why since change is not a priority and not in a roadmap.

Wouldn't ongoing improvements to cache performance and resource usage be on the roadmap?

2020-11-18 20:49 UTC, mongeron commented
Sorry for not updating this yet.

I've been busy with other issues, so I haven't managed to check the tests thoroughly. However, I'll take it under work as soon as I get the chance.

I'll open a new PR once I have test coverage fixed.