Purge urls filter
W3EDGE/w3-total-cache pull request #352
Opened 2021-03-25 10:35 UTC by diegofs-1989

Added a regex to the purge method.

2021-03-26 16:36 UTC, cssjoe requested changes
@diegofs-1989 There are some changes that revert recent updates (2 other files).  It appears that the new code change is only in `Cdnfsd_TransparentCDN_Engine.php`.  Please ensure that you checkout the latest `master` branch to only includes the new URL filter code.

2021-03-29 13:42 UTC, diegofs-1989 reviewed
Deleted repeated lines and kept the regex.

2021-03-29 20:52 UTC, cssjoe requested changes
Please see the comments made on the files changed.  Also, if you only need to validate the URL, you can use `if ( filter_var( $url, FILTER_VALIDATE_URL ) ) {` as the condition.

2021-03-29 20:52 UTC, cssjoe commented on Cdnfsd_TransparentCDN_Engine.php
> +		$url_pattern = "/https?:\/\/(www\.)?[-a-zA-Z0-9]{1,256}\.?[a-zA-Z0-9]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/";
The PCRE regex has an issue (Unknown modifier '/').  Review these tests:

```
$ php -r '$url = "https://www.exmaple.com/test-page?queryarg=123"; $url_pattern = "/https?:\/\/(www\.)?[-a-zA-Z0-9]{1,256}\.?[a-zA-Z0-9]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/"; var_dump( preg_match( $url_pattern, $url ) );'
Warning: preg_match(): Unknown modifier '/' in Command line code on line 1
bool(false)
```

When removing the two slashes in the pattern:
```
$ php -r '$url = "https://www.exmaple.com/test-page?queryarg=123"; $url_pattern = "/https?:\/\/(www\.)?[-a-zA-Z0-9]{1,256}\.?[a-zA-Z0-9]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&=]*)/"; var_dump( preg_match( $url_pattern, $url ) );'
int(1)
```

If you intended to have the slashes in the character class, then you need only one and need to either escape it or change your regex delimiter.

2021-03-29 20:52 UTC, cssjoe commented on Cdnfsd_Core.php
> -				case 'transparentcdn':
The changes in this file are not needed.  They may have been from an old copy.

2021-03-30 17:41 UTC, cssjoe requested changes
The file `Cdnfsd_Core.php` still needs to be reverted to the current version from our master branch.  There is also a minor code standard issue; a missing space before an opening brace.  See the other comments.  Thanks.

2021-03-30 17:41 UTC, cssjoe commented on Cdnfsd_TransparentCDN_Engine.php
> +			if ( filter_var( $url, FILTER_VALIDATE_URL ) ){
Minor: Missing space before opening brace.

2021-03-30 17:41 UTC, cssjoe commented on Cdnfsd_Core.php
> -				case 'transparentcdn':
This file still has formatting changes.  Please revert to the current copy in master: https://raw.githubusercontent.com/W3EDGE/w3-total-cache/master/Cdnfsd_Core.php

2021-03-31 13:38 UTC, cssjoe approved these changes
@diegofs-1989 Thank you for your contribution.  This update will be included in the upcoming release 2.1.2 in the next couple of days.

2021-03-31 13:39 UTC, merged