Update Cdn_Plugin.php
W3EDGE/w3-total-cache pull request #434
Opened 2021-09-28 08:19 UTC by hanicker

Execute purge on cdn only if hosting is enabled, to prevent unneded delays

2021-10-01 13:00 UTC, maxicus approved these changes

2021-10-04 14:59 UTC, cssjoe requested changes

2021-10-04 14:59 UTC, cssjoe commented on Cdn_Plugin.php
> +			if ($this->_config->get_string( 'cdn.uploads.enable' )) {
The setting is a boolean and not a string.  You can use the following:
```
if ( $this->_config->get_boolean( 'cdn.uploads.enable' ) ) {
```

2021-10-07 15:27 UTC, cssjoe approved these changes

2021-10-07 15:29 UTC, merged