Add notice when selecting CDN using CloudFront
W3EDGE/w3-total-cache pull request #540
Opened 2022-07-18 22:33 UTC by cssjoe

2022-07-19 16:35 UTC, mavas84 submitted a review, later dismissed
Exactly what is needed. I'll add the link for the article about the manual purge to avoid invalidations per path

2022-07-27 15:49 UTC, jacobd91 requested changes

2022-07-27 15:49 UTC, jacobd91 commented on Generic_Plugin_Admin.php
> +						)
For wp_kses should the <br /> tag be defined as an allowed tag?

2022-07-27 15:49 UTC, jacobd91 commented on Generic_Plugin_Admin.php
> +						),
For the sprintf, the argument count doesn't match the defined placeholders. Currently only 1 placeholder defined but 3 passed

2022-08-01 16:19 UTC, jacobd91 approved these changes
Reviewed and approved

2022-08-01 16:29 UTC, merged